server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuhaozzu/micro-service
          search-paths: config-server
          # username: liuhaozzu
          # password: ******
      label: master
      